server:
  port: 8088

# MinIO 配置
minio:
  endpoint: http://10.12.41.201:9000     # MinIO服务地址
  fileHost: http://10.12.41.201:9000    # 文件地址host
  bucketName: test              # 存储桶 bucket名称
  accessKey: minioadmin           # 用户名
  secretKey: minioadmin           # 密码

custom:
  minioListenedBucket: listenedtest # 自动下载 所监听的minio桶