
spring:
  application:
    name: scheduler
  rabbitmq:
    host: 192.168.118.129
    port: 5672
    virtual-host: /minio
    username: test
    password: 123456

  cloud:
    nacos:
      server-addr: 192.168.118.129:8848


server:
  port: 8890