version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: your-database
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
#    volumes:
#      - ./data:/var/lib/mysql
#      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306

  minio:
    image: minio/minio
    hostname: "minio"
    ports:
      - 9000:9000 # api 端口
      - 9001:9001 # 控制台端口
    environment:
      MINIO_ACCESS_KEY: admin    #管理后台用户名
      MINIO_SECRET_KEY: admin123 #管理后台密码，最小8个字符
#    volumes:
#      - ./docker/minio/data:/data               #映射当前目录下的data目录至容器内/data目录
#      - ./docker/minio/config:/root/.minio/     #映射配置目录

    # win 环境下
    volumes:
      - D:\\docker\\minio\\data:/data               #映射当前目录下的data目录至容器内/data目录
      - D:\\docker\\minio\\config:/root/.minio/     #映射配置目录

    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    privileged: true
    restart: always